### ISSUE TITLE
[QUESTION] How to exclude more than 3 "thing" on the hard-coded triple field ? 

### ISSUE THREAD

**Issue by Vaarlion** [AF-1/lms-virtuallibrarycreator#2]
Hi !
Sorry, this isn't a bug, and if it could evolve into a Feature request, it's not one right now.
I couldn't find a git issue template, but you made tags for it, so i hope it's OK ?

I'm trying to create virtual library for me and my family using the same unified music folder. I though this plugin would be great for that and i would be able to exclude many folder from their, and other from mine. I don't need it to be smart, just something i can quickly edit when i add something they don't need or the other way around.

Sadly, i can't select by type or by artist because there is a lot of compilation, Path make the most sense, album name would take more time but can work.

But right now, it look like it's limited to 3, hard-codded, field ? Is there any regex, or in-field list format i can use ?
Or is there something i have missed ? LMS is quite hard to find information on, so 100% possible this has already been replied somewhere else :(

Thank's !

## VERSION INFO
* LMS version:  8.4.0 - 1703166712
* OS (version): Docker
* Plugin version: 1.2.4
* Web skin/controller:  Material
* Browser (version): Firefox 121.0 (64-bit)

**Comment by AF-1** [comment]
Sorry for the delay. I don't spend much time on LMS and my plugins anymore. I'm already with one foot out the door.

It's true, 3 paths is the hard-coded max. With more paths the sql code would get quite complicated due to all their possible logical combinations (and/or).

If you don't mind a file level solution, maybe take a look at the *Simple Library Views* plugin. I don't use it so I don't know if it serves your purpose.

If you have a decent app to manage your music library that supports batch tagging: you could add the name of the family member to the _comment tags_ of music files that should not be part of that family member's virtual library. Not complicated to achieve and makes for easy filtering by comment tag. Would be a safe way to store your settings too so they "survive" renaming of folders or moving the music files elsewhere.
